name: Python CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
      uses: actions/checkout@v4

      -name: set up python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

      -name: install pytest
      run: pip install pytest

      -name: run pytest
      run: python -m pytest
      